service: video-editor

frameworkVersion: '2'

custom:
  bucketName: 111111111111111111

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-1
  httpApi:
    useProviderTags: true
  tags:
    proyecto: ${self:service}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
          Resource: arn:aws:s3:::${self:custom.bucketName}/files/*

functions:
  uploadfile:
    handler: lambda/uploadfile/index.handler
    memorySize: 128
    timeout: 5
    events:
      - httpApi:
          path: /uploadfile
          method: post
  extractvideo:
    handler: lambda/extractvideo/index.handler
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /extractvideo
          method: post
  applychanges:
    image: ffffffffffff.dkr.ecr.eu-west-1.amazonaws.com/video-editor@sha256:
    memorySize: 4096
    timeout: 600
